name: Auto Label New Issues
on:
  issues:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add To Do Label
        uses: andymckay/labeler@master
        with:
          add-labels: "To Do"
